export default [
  {
    id: 1,
    sourceCodeUrl: 'https://github.com/davidk55/simple-color-converter',
    title: 'Simple Color Converter',
    img: 'project-1.png',
    tags: ['Clipboard API', 'Webpack', 'SCSS'],
    demoUrl: 'https://simple-color-converter.netlify.app/',
  },
  {
    id: 2,
    sourceCodeUrl: 'https://github.com/davidk55/simple-pomodoro-timer',
    title: 'Simple Pomodoro Timer',
    img: 'project-2.png',
    tags: ['Keyboad Events', 'Date API'],
    demoUrl: 'https://simple-pomodoro-timer-davidk55.netlify.app/',
  },
  {
    id: 3,
    sourceCodeUrl: 'https://github.com/davidk55/simple-to-do-list',
    title: 'Simple To-Do List',
    img: 'project-3.png',
    tags: ['Local Storage', 'Drag and Drop API'],
    demoUrl: 'https://simple-to-do-list-davidk55.netlify.app/',
  },
  {
    id: 4,
    sourceCodeUrl: 'https://github.com/davidk55/mario-clone',
    title: 'Mario Clone',
    img: 'project-4.png',
    tags: ['Object Oriented JS', 'Canvas API'],
    demoUrl: 'https://mario-clone.netlify.app/',
  },
  {
    id: 5,
    sourceCodeUrl: 'https://github.com/davidk55/simple-weather-display',
    title: 'Simple Weather Display',
    img: 'project-5.png',
    tags: ['Netlify Functions', 'Fetch API'],
    demoUrl: 'https://simple-weather-display.netlify.app/',
  },
  {
    id: 6,
    sourceCodeUrl: 'https://github.com/davidk55/simple-calculator',
    title: 'Simple Calculator',
    img: 'project-6.png',
    tags: ['React', 'Tailwind CSS'],
    demoUrl: 'https://simple-calculator-davidk55.netlify.app/',
  },
  {
    id: 7,
    sourceCodeUrl: 'https://github.com/davidk55/simple-form',
    title: 'Simple Form',
    img: 'project-7.png',
    tags: ['React', 'Input Validation'],
    demoUrl: 'https://simple-form-davidk55.netlify.app/',
  },
  {
    id: 8,
    sourceCodeUrl: 'https://github.com/davidk55/currency-converter',
    title: 'Currency Converter',
    img: 'project-8.png',
    tags: ['React', 'Axios', 'Typescript'],
    demoUrl: 'https://currency-converter-davidk55.netlify.app/',
  },
];
